version: "3.5"

services:
    obras:
        build: .
        depends_on:
            - pg
        networks:
            - obras_network

    pg:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - obras_network

networks:
    obras_network:
        name: obras_network
        driver: bridge

volumes:
    pg_data:
