version: "3.5"

x-shared-environment: &commonEnv
    POSTGRES_DB: "single_sign_on"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_PORT: 5432

services:
    sso:
        build: .
        volumes:
            - ./sso:/app/src/sso:cached
        environment: *commonEnv
        depends_on:
            - pg
            - redis
        networks:
            - sso_network

    pg:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment: *commonEnv
        ports:
            - "5432:5432"
        networks:
            - sso_network

    redis:
        image: redis
        environment: *commonEnv
        networks:
            - sso_network

networks:
    sso_network:
        name: sso_network
        driver: bridge

volumes:
    pg_data:
