version: "3.5"

services:
    sso:
        build: .
        volumes:
            - ./sso:/app/src/sso:cached

        depends_on:
            - pg
            - redis
        networks:
            - sso_network

    pg:
        image: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - sso_network

    redis:
        image: redis
        networks:
            - sso_network

networks:
    sso_network:
        name: sso_network
        driver: bridge

volumes:
    pg_data:
